all:
	gcc -Wall -g life3d.c -o life3d
debug:
	gcc -Wall -DDEBUG -g life3d.c -o life3d
iteration:
	gcc -Wall -DITERATION -g life3d.c -o life3d
opt:
	gcc -Wall -O3 life3d.c -o life3d 
optiter:
	gcc -Wall -O3 -DITERATION -o life3d life3d.c
